# Generated by Django 2.2 on 2019-08-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FieldStaff',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='フィールドスタッフ職')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='FoulMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='反則名')),
                ('is_penalty', models.BooleanField(verbose_name='重度な反則か')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Half',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='時間')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchSwitchEventType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                (
                    'name',
                    models.CharField(max_length=35, verbose_name='試合中交替/入替イベント名称'),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='試合形式名称')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('family_name', models.CharField(max_length=35, verbose_name='姓')),
                ('first_name', models.CharField(max_length=35, verbose_name='名')),
                ('birthday', models.DateField(null=True, verbose_name='誕生日')),
                ('in_our_team', models.Field()),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('number', models.IntegerField(verbose_name='背番号')),
                ('name', models.CharField(max_length=35, verbose_name='ポジション名')),
                ('is_front_row', models.BooleanField(verbose_name='フロントロー')),
            ],
            options={'db_table': 'player_position'},
        ),
        migrations.CreateModel(
            name='ScoringMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='得点手法名')),
                ('point', models.IntegerField(verbose_name='得点')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='役職名')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='チームグループ名')),
                ('is_my_team', models.BooleanField(verbose_name='自チームグループか')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='TeamOnMatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='チーム名')),
                (
                    'team_group',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='rugby.TeamGroup',
                        verbose_name='チームグループ',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='チーム名')),
                (
                    'team_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.TeamGroup',
                        verbose_name='チームグループ',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                (
                    'height',
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name='身長'
                    ),
                ),
                (
                    'weight',
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name='体重'
                    ),
                ),
                (
                    'player_position',
                    models.ManyToManyField(
                        related_name='ポジション', to='rugby.PlayerPosition'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='PlayerOnMatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('position_number', models.PositiveIntegerField(verbose_name='背番号')),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Member',
                        verbose_name='メンバー',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rugby.TeamOnMatch',
                        verbose_name='所属チーム',
                    ),
                ),
            ],
            options={
                'unique_together': {('team', 'member'), ('team', 'position_number')}
            },
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='経過時間')),
                ('name', models.CharField(max_length=35, verbose_name='イベント名')),
                (
                    'half',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Half',
                        verbose_name='ハーフ',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='member',
            name='player_profile',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='rugby.PlayerProfile',
                verbose_name='選手プロフィール',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='staff_position',
            field=models.ManyToManyField(related_name='役職', to='rugby.StaffPosition'),
        ),
        migrations.CreateModel(
            name='MatchSwitchEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='経過時間')),
                (
                    'event_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.MatchSwitchEventType',
                        verbose_name='試合中交替/入替イベント種別',
                    ),
                ),
                (
                    'half',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Half',
                        verbose_name='ハーフ',
                    ),
                ),
                (
                    'in_member',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='match_in',
                        to='rugby.PlayerOnMatch',
                        verbose_name='出場メンバー',
                    ),
                ),
                (
                    'out_member',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='match_out',
                        to='rugby.PlayerOnMatch',
                        verbose_name='退場メンバー',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='MatchScoringEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='経過時間')),
                ('is_no_kick', models.BooleanField(verbose_name='キック蹴らず')),
                (
                    'half',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Half',
                        verbose_name='ハーフ',
                    ),
                ),
                (
                    'method',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.ScoringMethod',
                        verbose_name='得点手法',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.PlayerOnMatch',
                        verbose_name='得点メンバー',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='MatchPatternedEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='経過時間')),
                (
                    'event_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.PatternType',
                        verbose_name='試合中交替/入替イベント種別',
                    ),
                ),
                (
                    'half',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Half',
                        verbose_name='ハーフ',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='MatchFoulEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('duration', models.DurationField(verbose_name='経過時間')),
                (
                    'card_choice',
                    models.CharField(
                        choices=[
                            ('safe', 'No Card'),
                            ('yellow', 'Yellow Card'),
                            ('red', 'Red Card'),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    'half',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Half',
                        verbose_name='ハーフ',
                    ),
                ),
                (
                    'method',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.FoulMethod',
                        verbose_name='反則手法',
                    ),
                ),
                (
                    'out_event',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.MatchSwitchEvent',
                        verbose_name='退場イベント',
                    ),
                ),
                (
                    'penalty_try',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.MatchScoringEvent',
                        verbose_name='ペナルティトライイベント',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.PlayerOnMatch',
                        verbose_name='反則メンバー',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('held_datetime', models.DateTimeField()),
                (
                    'assistant_referee',
                    models.ManyToManyField(
                        related_name='match_assistant_referee',
                        to='rugby.Member',
                        verbose_name='アシスタントレフリー',
                    ),
                ),
                (
                    'left_team',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='match_left',
                        to='rugby.TeamOnMatch',
                        verbose_name='左チーム',
                    ),
                ),
                (
                    'match_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.MatchType',
                        verbose_name='試合種別',
                    ),
                ),
                (
                    'referee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='match_referee',
                        to='rugby.Member',
                        verbose_name='レフリー',
                    ),
                ),
                (
                    'right_team',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='match_right',
                        to='rugby.TeamOnMatch',
                        verbose_name='右チーム',
                    ),
                ),
                (
                    'touch_judge',
                    models.ManyToManyField(
                        related_name='match_touch_judge',
                        to='rugby.Member',
                        verbose_name='タッチジャッジ',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='half',
            name='match',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='rugby.Match',
                verbose_name='試合',
            ),
        ),
        migrations.CreateModel(
            name='StaffOnMatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                (
                    'field_staff',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.FieldStaff',
                        verbose_name='フィールドスタッフ職',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='rugby.Member',
                        verbose_name='メンバー',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rugby.TeamOnMatch',
                        verbose_name='所属チーム',
                    ),
                ),
            ],
            options={'unique_together': {('team', 'member')}},
        ),
        migrations.AlterUniqueTogether(
            name='half', unique_together={('match', 'number')}
        ),
    ]
