# Generated by Django 2.2 on 2019-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FoulMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='反則名')),
                ('is_penalty', models.BooleanField(verbose_name='重度な反則か')),
            ],
            options={'verbose_name_plural': '反則', 'db_table': 'rugby_foul_method'},
        ),
        migrations.CreateModel(
            name='MatchSwitchEventType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                (
                    'name',
                    models.CharField(max_length=35, verbose_name='試合中交替/入替イベント名称'),
                ),
            ],
            options={
                'verbose_name_plural': '試合中交替/入替イベント種別',
                'db_table': 'rugby_match_switch_event_type',
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='試合形式名称')),
            ],
            options={'verbose_name_plural': '試合形式', 'db_table': 'rugby_match_type'},
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='イベント名')),
            ],
            options={
                'verbose_name_plural': '試合イベントパターン',
                'db_table': 'rugby_pattern_type',
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('number', models.IntegerField(verbose_name='背番号')),
                ('name', models.CharField(max_length=35, verbose_name='ポジション名')),
                ('is_front_row', models.BooleanField(verbose_name='フロントロー')),
            ],
            options={
                'verbose_name_plural': 'ポジション',
                'db_table': 'rugby_player_position',
            },
        ),
        migrations.CreateModel(
            name='ScoringMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='得点手法名')),
                ('point', models.IntegerField(verbose_name='得点')),
            ],
            options={'verbose_name_plural': '得点手法', 'db_table': 'rugby_scoring_method'},
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='更新日時'),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
                ),
                ('name', models.CharField(max_length=35, verbose_name='役職名')),
            ],
            options={'verbose_name_plural': '役職', 'db_table': 'rugby_staff_position'},
        ),
    ]
