# Generated by Django 2.2 on 2019-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('master', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='scoringmethod',
            name='short_letter',
            field=models.CharField(default='T', max_length=2, verbose_name='得点コード'),
            preserve_default=False,
        )
    ]
