version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose up -d --build
      - run:
          name: Run tests
          command: |
            docker-compose exec django python manage.py migrate && \
            docker-compose exec django python manage.py test

