version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Copy .env File
          command: cp .env.testing .env
      - run:
          name: Build Docker Image
          command: docker-compose up -d --build
      - run:
          name: Run tests
          command: |
            docker-compose exec mysql mysql.server restart
            docker-compose exec mysql mysql -uxv_rugby -pxv_rugby
            docker-compose exec django python manage.py migrate
            docker-compose exec django python manage.py test

