# Generated by Django 2.2 on 2019-08-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('member', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='member', name='in_our_team'),
        migrations.AddField(
            model_name='member',
            name='team_group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='member.TeamGroup',
                verbose_name='所属チームグループ',
            ),
        ),
    ]
