# Generated by Django 2.2 on 2019-08-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('member', '0003_auto_20190810_0216')]

    operations = [
        migrations.RemoveField(model_name='member', name='player_profile'),
        migrations.AddField(
            model_name='playerprofile',
            name='member',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='member.Member',
                verbose_name='人員',
            ),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='player_position',
            field=models.ManyToManyField(
                to='master.PlayerPosition', verbose_name='ポジション'
            ),
        ),
    ]
