# Generated by Django 2.2 on 2019-08-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('member', '0004_auto_20190810_0236')]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='member',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='member.Member',
                unique=True,
                verbose_name='人員',
            ),
        )
    ]
